spring:
  application:
    name: HRBank
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  profiles:
    active: prod

# 환경 변수로 설정할 값
env:
  DATABASE_PUBLIC_URL: ${DATABASE_PUBLIC_URL}
  DATABASE_URL: ${DATABASE_URL}
  PGDATA: ${PGDATA}
  PGDATABASE: ${PGDATABASE}
  PGHOST: ${PGHOST}
  PGPASSWORD: ${PGPASSWORD}
  PGPORT: ${PGPORT}
  PGUSER: ${PGUSER}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: public

hrbank:
  storage:
    type: local
    local:
      paths:
        binary-content-path: .hrbank/binaryContentStorage
        employees-path: .hrbank/employeesStorage
        error-log-path: .hrbank/errorLogStorage