spring:
  application:
    name: HRBank
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: ${POSTGRES_USER}  # 환경 변수 사용
    password: ${POSTGRES_PASSWORD}  # 환경 변수 사용
    driver-class-name: org.postgresql.Driver
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중이라면 'update' 사용
    show-sql: false
    properties:
      hibernate:
        default_schema: public

hrbank:
  storage:
    type: local
    local:
      paths:
        binary-content-path: .hrbank/binaryContentStorage
        employees-path: .hrbank/employeesStorage
        error-log-path: .hrbank/errorLogStorage
